[package]
name = "my_app"
version = "0.1.0"
authors = ["ServiceStack, Inc. <team@servicestack.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
