version: "3.9"
services:
  ${APP_NAME}:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    depends_on:
      - ${APP_NAME}-litestream
    restart: always
    network_mode: bridge
    ports:
      - "80"
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEPLOY_API: ${DEPLOY_API}
      DEPLOY_CDN: ${DEPLOY_CDN}
    volumes:
      - ${APP_NAME}-mydb:/app/App_Data
  ${APP_NAME}-litestream:
    image: litestream/litestream
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /usr/local/bin/litestream restore -if-db-not-exists -o /data/MyApp.sqlite abs://${AZURE_STORAGEACCOUNT}@${AZURE_CONTAINER}/MyApp.sqlite
        /usr/local/bin/litestream replicate /data/MyApp.sqlite abs://${AZURE_STORAGEACCOUNT}@${AZURE_CONTAINER}/MyApp.sqlite
    environment:
      LITESTREAM_AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
    volumes:
      - ${APP_NAME}-mydb:/data

volumes:
  ${APP_NAME}-mydb:
